services:
  frontend:
    build: ./interface
    container_name: frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    links:
      - backend

  backend:
    build: ./api
    container_name: backend
    env_file: ./api/.env
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db

  db:
    image: dgraph/standalone:v21.03.2
    container_name: db
    expose: [9080]
